// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwGlJeAzX0RUhPL4dvgsRRKTOFHWi7HQ',
    appId: '1:913272988568:web:11069d11250211c02881ed',
    messagingSenderId: '913272988568',
    projectId: 'todolist-81e88',
    authDomain: 'todolist-81e88.firebaseapp.com',
    storageBucket: 'todolist-81e88.appspot.com',
    measurementId: 'G-DES6Y9DBLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhePQeGZFTFZQ5TBCLftwD5z717Y4m0Ds',
    appId: '1:913272988568:android:f8841621d01830e22881ed',
    messagingSenderId: '913272988568',
    projectId: 'todolist-81e88',
    storageBucket: 'todolist-81e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1mXX6exyXgHMHjkZovzUyGLFdvW6gTk',
    appId: '1:913272988568:ios:c380f73c8cec731d2881ed',
    messagingSenderId: '913272988568',
    projectId: 'todolist-81e88',
    storageBucket: 'todolist-81e88.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_1mXX6exyXgHMHjkZovzUyGLFdvW6gTk',
    appId: '1:913272988568:ios:05c73fcc8437b8372881ed',
    messagingSenderId: '913272988568',
    projectId: 'todolist-81e88',
    storageBucket: 'todolist-81e88.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
